#!/usr/bin/env bash
interval=5
directory="$HOME/Pictures/Wallpapers"

lockfile="$HOME/.config/niri/scripts/wallpaper.lock"

exec 200>"$lockfile"
flock -n 200 || { echo "Wallpaper script already running."; exit 1; }

while true; do
  find "$directory" -type f | shuf | while read -r img; do
     echo "Setting wallpaper: $img"
     swww img --transition-type="wipe" --transition-angle=30 --transition-fps=144 "$img"
     sleep "${interval}m"
  done
done
